name: Release - Github

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Release
        uses: xresloader/upload-to-github-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          file: "server/target/web3-monitoring-agent.jar"
          tags: true
          draft: false
          prerelease: false
          overwrite: true
          verbose: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
